# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: log_schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'log_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10log_schema.proto\x12\x05\x66lare\"\x89\x01\n\nUnifiedLog\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0f\n\x07host_id\x18\x02 \x01(\t\x12$\n\x06system\x18\x03 \x01(\x0b\x32\x12.flare.SystemEventH\x00\x12%\n\x07network\x18\x04 \x01(\x0b\x32\x12.flare.NetworkFlowH\x00\x42\n\n\x08log_type\"g\n\x0bSystemEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\x05\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x12\n\nlogon_type\x18\x03 \x01(\x05\x12\x14\n\x0cprocess_name\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"}\n\x0bNetworkFlow\x12\x11\n\tsource_ip\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65st_ip\x18\x02 \x01(\t\x12\x11\n\tdest_port\x18\x03 \x01(\x05\x12\x10\n\x08protocol\x18\x04 \x01(\t\x12\x12\n\nflow_bytes\x18\x05 \x01(\x02\x12\x11\n\tdirection\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNIFIEDLOG']._serialized_start=28
  _globals['_UNIFIEDLOG']._serialized_end=165
  _globals['_SYSTEMEVENT']._serialized_start=167
  _globals['_SYSTEMEVENT']._serialized_end=270
  _globals['_NETWORKFLOW']._serialized_start=272
  _globals['_NETWORKFLOW']._serialized_end=397
# @@protoc_insertion_point(module_scope)
